package question8;

public class TryWithoutCatch {

	public static void main(String[] args) {
		try {
			System.out.println("vishal ");
		} finally {
			System.out.println("Yes, by utilizing a finally block, we can have a try without a catch block. ");
		}
	}
}



